<#
.SYNOPSIS
  Disable throttling on more than 5000 items list
.DESCRIPTION
  This script uses as input csv file generated by ShareGate or other powershell script with required Title column and SiteAddress column (site url)
.PARAMETER <paramName>
   <Description of script parameter>
.EXAMPLE
   Provide file name in $InvFile variable and put this file into the same folder as script located.
#>

if ( (Get-PSSnapin -Name Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue) -eq $null ) { 
    Add-PsSnapin Microsoft.SharePoint.PowerShell 
} 

$InvFile = "Lists with more than 5000 items.csv" 

# Get Data from Inventory CSV File and check if file exist.
$FileExists = (Test-Path $InvFile -PathType Leaf) 
if ($FileExists) { 
    "Loading $InvFile for processing..." 
    $tblData = Import-CSV $InvFile 
}
else { 
    "$InvFile not found - stopping import!" 
    exit 
}

# Loop through Webs and change throttling to false on SharePoint lists

foreach ($row in $tblData) 
{
    #"Getting Web for " + $row.'SiteAddress'.ToString()
    $WebSite = Get-SPWeb $row.'SiteAddress'
    Write-Host "Web URL" + $WebSite
    $List = $WebSite.Lists[$row.'Title']
    $List.EnableThrottling = $false
	Write-host "Throttling is in state" : $List.EnableThrottling -f green
    $List.Update()
}
$WebSite.Dispose()